### ISSUE TITLE
toSession unhandled session token

### ISSUE THREAD

**Issue by decima** [ory/kratos-client-php#4]
Finally managed to register/login/logout, now I want to make a profile page, and i'm calling the toSession method. 

But the toSession requires a X-Session-Token which is not really clear to me. So first I made my own call:
```php
    public function getCurrentAuthenticatedUser(Request $request)
    {
        $client = new Client(["base_uri" => $this->getBrowserUrl()]);
        return $client->get("/sessions/whoami", ["headers" => $request->headers->all()]);
    }
```
It works but I would like to use the toSession method, so after digging into it, I've discover a set of [apiKeys in the Configuration](https://github.com/ory/kratos-client-php/blob/60f490f07f3778fc8be7f01b9bc0910ca29a36c4/lib/Configuration.php#L133) and saw there is a begin of code in the publicApi, but seems like something is missing:

https://github.com/ory/kratos-client-php/blob/60f490f07f3778fc8be7f01b9bc0910ca29a36c4/lib/Api/PublicApi.php#L7441-L7445

Am I doing something wrong? can't find any explanation about this X-Session-Token.

**Comment by aeneasr** [comment]
Hello, the session token is for native/mobile apps. For browser apps you must use cookies in toSession! I am not sure if the generated client supports that out of the box. Basically, you need to forward the HTTP Cookie header which ends up at your server to Kratos!

**Comment by decima** [comment]
That's what I did:
```
    public function getCurrentAuthenticatedUser(Request $request):Session
    {
        $response = $this->client->get(
            "/sessions/whoami",
            [
                "base_uri" => $this->getBrowserUrl(),
                "headers" => ["cookie"=>$request->headers->get("cookie")]
            ]
        );
        return new Session(
            json_decode($response->getBody()->getContents(), true)
        );
    }
```

**Comment by aeneasr** [comment]
Ah ok, I see, the problem is that the `toSession` method does not support the header property?

https://github.com/ory/kratos-client-php/blob/60f490f07f3778fc8be7f01b9bc0910ca29a36c4/lib/Api/PublicApi.php#L7387

Other clients do have this parameter, for example:

https://github.com/ory/kratos-client-go/blob/eb6f01330bbbb62ef6a731f7bb7b931e7a7ad0db/api_v0alpha1.go#L2602

However, I looked a bit into the PHP code base, it looks like you can use this?

https://github.com/ory/kratos-client-php/blob/60f490f07f3778fc8be7f01b9bc0910ca29a36c4/lib/Api/V0alpha1Api.php#L3611
